server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
  #声明自己是服务端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
    #获取属性的方法为 ${XX.xx}
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/